package GUI;
import Class.*;
public class CarCard extends javax.swing.JPanel {

    private MainPage main;
    private Car car;
    public CarCard() {
        
        initComponents();
    }
    public CarCard(MainPage main, Car car) {
        this.main = main;
        this.car = car;
        initComponents();
        priceTag.setText(String.valueOf(car.getPrice()));
        carName.setText(String.valueOf(car.getName()));
        picture.setIcon(car.getImg());
   }
    public Car getCar(){
        return car;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailbutton = new javax.swing.JButton();
        testDriveButton = new javax.swing.JButton();
        priceTag = new javax.swing.JLabel();
        carName = new javax.swing.JLabel();
        BookingButton = new javax.swing.JButton();
        Carpicture = new javax.swing.JPanel();
        picture = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        detailbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        detailbutton.setText("Detail");
        detailbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailbuttonActionPerformed(evt);
            }
        });

        testDriveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        testDriveButton.setText("Test drive");
        testDriveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testDriveButtonActionPerformed(evt);
            }
        });

        priceTag.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        priceTag.setText("Price");

        carName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        carName.setText("carname");

        BookingButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BookingButton.setText("Booking");
        BookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingButtonActionPerformed(evt);
            }
        });

        picture.setText("picture");

        javax.swing.GroupLayout CarpictureLayout = new javax.swing.GroupLayout(Carpicture);
        Carpicture.setLayout(CarpictureLayout);
        CarpictureLayout.setHorizontalGroup(
            CarpictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarpictureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CarpictureLayout.setVerticalGroup(
            CarpictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarpictureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(priceTag, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BookingButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testDriveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailbutton)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Carpicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(carName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Carpicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailbutton)
                    .addComponent(testDriveButton)
                    .addComponent(priceTag)
                    .addComponent(BookingButton))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void testDriveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testDriveButtonActionPerformed
        main.testdriveforcard();
    }//GEN-LAST:event_testDriveButtonActionPerformed

    private void detailbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailbuttonActionPerformed
       main.addDetail(this);       
    }//GEN-LAST:event_detailbuttonActionPerformed

    private void BookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingButtonActionPerformed
        main.bokingforcard();
    }//GEN-LAST:event_BookingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingButton;
    private javax.swing.JPanel Carpicture;
    private javax.swing.JLabel carName;
    private javax.swing.JButton detailbutton;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel priceTag;
    private javax.swing.JButton testDriveButton;
    // End of variables declaration//GEN-END:variables
}
