package GUI;
import Class.*;
public class CarCard extends javax.swing.JPanel {

    private MainPage main;
    private Vehicle vhi;
    public CarCard() {
        initComponents();
    }
    public CarCard(MainPage main, Vehicle vhi) {
        this.main = main;
        this.vhi = vhi;
        initComponents();
        priceTag.setText(String.valueOf(vhi.getPrice()));
        carName.setText(String.valueOf(vhi.getName()));
    }
    public Vehicle getCar(){
        return vhi;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picture = new javax.swing.JLabel();
        detailbutton = new javax.swing.JButton();
        testDriveButton = new javax.swing.JButton();
        priceTag = new javax.swing.JLabel();
        carName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        picture.setText("picture");

        detailbutton.setText("Detail");
        detailbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailbuttonActionPerformed(evt);
            }
        });

        testDriveButton.setText("Test drive");
        testDriveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testDriveButtonActionPerformed(evt);
            }
        });

        priceTag.setText("Price");

        carName.setText("carname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceTag, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(testDriveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(detailbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(carName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailbutton)
                    .addComponent(testDriveButton)
                    .addComponent(priceTag))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void testDriveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testDriveButtonActionPerformed
        BookingAndTestDrive btd1 = new BookingAndTestDrive();
        btd1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_testDriveButtonActionPerformed

    private void detailbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailbuttonActionPerformed
        
       main.addDetail();

    }//GEN-LAST:event_detailbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carName;
    private javax.swing.JButton detailbutton;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel priceTag;
    private javax.swing.JButton testDriveButton;
    // End of variables declaration//GEN-END:variables
}
