/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;
import Class.*;
/**
 *
 * @author admin
 */
public class DetailCar extends javax.swing.JInternalFrame {
    private Car car;
    public DetailCar(Car car) {
        initComponents();
        this.car = car;
        nameL.setText("Car name : " + car.getName());
        typeL.setText("Type : " + car.getType());
        capaL.setText("Capacity : " + car.getCapacity());
        ccL.setText("CC : " + car.getCC());
        doorL.setText("Door : " +  car.getDoor());
        wheelL.setText("Wheel : " + car.getWheel());
        priceL.setText("Price : " + car.getPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        typeL = new javax.swing.JLabel();
        nameL = new javax.swing.JLabel();
        capaL = new javax.swing.JLabel();
        wheelL = new javax.swing.JLabel();
        doorL = new javax.swing.JLabel();
        ccL = new javax.swing.JLabel();
        priceL = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Picture");

        typeL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        typeL.setText("Type:");

        nameL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameL.setText("Car name:");

        capaL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        capaL.setText("Capacity:");

        wheelL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        wheelL.setText("Wheel:");

        doorL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        doorL.setText("Door:");

        ccL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ccL.setText("CC:");

        priceL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        priceL.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priceL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wheelL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doorL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capaL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(nameL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(typeL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(capaL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ccL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doorL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wheelL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priceL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capaL;
    private javax.swing.JLabel ccL;
    private javax.swing.JLabel doorL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameL;
    private javax.swing.JLabel priceL;
    private javax.swing.JLabel typeL;
    private javax.swing.JLabel wheelL;
    // End of variables declaration//GEN-END:variables
}
