package GUI;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import Class.TestConnection;

public class managecar extends javax.swing.JInternalFrame {
    TestConnection db;
    /**
     * Creates new form managecar
     */
    public managecar() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        DefaultTableModel model = null;
        try {
            db = new TestConnection();
            ResultSet rs = db.getConnect("select * from car");
            String[] colname = {"id", "name", "type", "cc", "price", "stock", "wheel", "door", "capacity"};
            int i = 0;
            model = new DefaultTableModel(colname, 0);
            while (rs.next()) {
                i++;
                String id = rs.getString("id");
                String name = rs.getString("name");
                String type = rs.getString("type");
                String cc = rs.getString("cc");
                String price = rs.getString("price");
                String stock = rs.getString("stock");
                String wheel = rs.getString("wheel");
                String door = rs.getString("door");
                String capacity = rs.getString("capacity");
                String[] row = {id, name, type, cc, price, stock, wheel, door, capacity};
                model.addRow(row);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Car");
        setMinimumSize(new java.awt.Dimension(1077, 687));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1077, 690));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(569, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
